
export const GROUPS_START_LOADING = "GROUPS_START_LOADING"
export type GROUPS_START_LOADING_TYPE = typeof GROUPS_START_LOADING

export const GROUPS_LOAD_SUCCESS = "GROUPS_LOAD_SUCCESS"
export type GROUPS_LOAD_SUCCESS_TYPE = typeof GROUPS_LOAD_SUCCESS

export const GROUPS_LOAD_FAILED = "GROUPS_LOAD_FAILED"
export type GROUPS_LOAD_FAILED_TYPE = typeof GROUPS_LOAD_FAILED


export const HIGHLIGHTS_START_LOADING = "HIGHLIGHTS_START_LOADING"
export type HIGHLIGHTS_START_LOADING_TYPE = typeof HIGHLIGHTS_START_LOADING

export const HIGHLIGHTS_LOAD_SUCCESS = "HIGHLIGHTS_LOAD_SUCCESS"
export type HIGHLIGHTS_LOAD_SUCCESS_TYPE = typeof HIGHLIGHTS_LOAD_SUCCESS

export const HIGHLIGHTS_LOAD_FAILED = "HIGHLIGHTS_LOAD_FAILED"
export type HIGHLIGHTS_LOAD_FAILED_TYPE = typeof HIGHLIGHTS_LOAD_FAILED
