
export const LIVE_START_LOADING = "LIVE_START_LOADING"
export type LIVE_START_LOADING_TYPE = typeof LIVE_START_LOADING

export const LIVE_LOAD_SUCCESS = "LIVE_LOAD_SUCCESS"
export type LIVE_LOAD_SUCCESS_TYPE = typeof LIVE_LOAD_SUCCESS

export const LIVE_LOAD_FAILED = "LIVE_LOAD_FAILED"
export type LIVE_LOAD_FAILED_TYPE = typeof LIVE_LOAD_FAILED
