
export const SPORT_START_LOADING = "SPORT_START_LOADING"
export type SPORT_START_LOADING_TYPE = typeof SPORT_START_LOADING

export const SPORT_LOAD_SUCCESS = "SPORT_LOAD_SUCCESS"
export type SPORT_LOAD_SUCCESS_TYPE = typeof SPORT_LOAD_SUCCESS

export const SPORT_LOAD_FAILED = "SPORT_LOAD_FAILED"
export type SPORT_LOAD_FAILED_TYPE = typeof SPORT_LOAD_FAILED
