
export const SOON_START_LOADING = "SOON_START_LOADING"
export type SOON_START_LOADING_TYPE = typeof SOON_START_LOADING

export const SOON_LOAD_SUCCESS = "SOON_LOAD_SUCCESS"
export type SOON_LOAD_SUCCESS_TYPE = typeof SOON_LOAD_SUCCESS

export const SOON_LOAD_FAILED = "SOON_LOAD_FAILED"
export type SOON_LOAD_FAILED_TYPE = typeof SOON_LOAD_FAILED
