
export const LANDING_START_LOADING = "LANDING_START_LOADING"
export type LANDING_START_LOADING_TYPE = typeof LANDING_START_LOADING

export const LANDING_LOAD_SUCCESS = "LANDING_LOAD_SUCCESS"
export type LANDING_LOAD_SUCCESS_TYPE = typeof LANDING_LOAD_SUCCESS

export const LANDING_LOAD_FAILED = "LANDING_LOAD_FAILED"
export type LANDING_LOAD_FAILED_TYPE = typeof LANDING_LOAD_FAILED
